---
- name: demo ansible playbook
  hosts: all
  gather_facts: no

  tasks:
    - name: task1
      ios_command:
        commands: "sh run"
      register: show_ip
    - debug: var=show_ip.stdout_lines
                      
    - name: chạy lệnh show version bao gồm IOS
      ios_command:
        commands: show version
        wait_for: result[0] contains IOS
    - name: chạy lệnh yêu cầu trả lời prompt
      ios_command:
        commands:
         - command: 'clear counters GigabitEthernet0/1'
           prompt: 'Clear "show interface" counters on this interface \[confirm\]'
           answer: 'y'
         - command: 'clear counters GigabitEthernet0/2'
           prompt: '[confirm]'
           answer: "\r"

