---
- name: DS
  hosts: DS
  gather_facts: no
  
  tasks:
    - name: tao vlan
      ios_vlan:
        aggregate: 
          - { vlan_id : 10 }
          - { vlan_id : 20 }
          - { vlan_id : 201 }
          - { vlan_id : 202 }
          - { vlan_id : 203 }
          - { vlan_id : 204 }
          - { vlan_id : 205 }
    - name: Show vlan
      ios_command:
        commands:
          - show vlan
          
          
      register: show_ip
    - name: cauhinh
      ios_config:
        lines:
          - spanning-tree mode rapid-pvst
          
    - name: mode trunk
      ios_config:
        parents:
          - int range e0/2-3
        lines:
          - sw trunk en dot1Q
          - sw mode trunk
    - name: mode trunk
      ios_config:
        parents:
          - int range e1/0
        lines:
          - sw trunk en dot1Q
          - sw mode trunk
    - debug: var=show_ip.stdout_lines
- name: HSRP DS1
  hosts: DS1
  gather_facts: no
  tasks:
    - name: HSRP 201
      ios_config:
        parents:
          - int vlan 201
        lines:
          - ip address 172.18.18.3 255.255.254.0
          - standby 201 ip 172.18.18.1
          - standby 201 priority 150
          - standby 201 preempt
          - no shut
    - name: HSRP 202
      ios_config: 
        parents: 
          - int vlan 202 
        lines: 
          - ip address 172.18.20.3 255.255.254.0 
          - standby 202 ip 172.18.20.1
          - standby 202 priority 100 
          - standby 202 preempt
          - no shut
    - name: HSRP 203
      ios_config: 
        parents: 
          - int vlan 203 
        lines: 
          - ip address 172.18.22.3 255.255.254.0 
          - standby 203 ip 172.18.22.1
          - standby 203 priority 150 
          - standby 203 preempt
          - no shut
    - name: set OSPF # cài đặt OSPF
      ios_config:
        parents: # vào mode config của lệnh dưới
          - router ospf 1
        lines: # các lệnh sẽ thực hiện
          - router-id 3.3.3.3
    - name: HSRP 204
      ios_config: 
        parents: 
          - int vlan 204 
        lines: 
          - ip address 172.18.24.3 255.255.255.0 
          - standby 204 ip 172.18.24.1
          - standby 204 priority 100
          - standby 204 preempt
          - no shut


    - name: Set interface e0/1
      ios_config:
        parents:
          - int e0/1
        lines:
          - no sw
          - no sh
          - ip address 172.16.12.2 255.255.255.0
          - do wr
    - name: Set interface e1/1
      ios_config:
        parents:
          - int e1/1
        lines:
          - no sw
          - no sh
          - ip address 172.16.14.2 255.255.255.0
          - do wr
    - name: OSPF 
      ios_config:
        parents:
          - router ospf 1
        lines:
          - network 172.18.0.0 0.0.255.255 area 0
          - network 172.16.0.0 0.0.255.255 area 0
          - do wr
########################################################
- name: HSRP DS2
  hosts: DS2
  gather_facts: no
  tasks:
    - name: set OSPF # cài đặt OSPF
      ios_config:
        parents: # vào mode config của lệnh dưới
          - router ospf 1
        lines: # các lệnh sẽ thực hiệnno
          - router-id 4.4.4.4
    - name: OSPF 
      ios_config:
        parents:
          - router ospf 1
        lines:
          - network 172.18.0.0 0.0.255.255 area 0
          - network 172.16.0.0 0.0.255.255 area 0
          - do wr
    - name: HSRP 201
      ios_config:
        parents:
          - int vlan 201
        lines:
          - ip address 172.18.18.2 255.255.254.0
          - standby 201 ip 172.18.18.1
          - standby 201 priority 100
          - standby 201 preempt
          - no shut
    - name: HSRP 202
      ios_config: 
        parents: 
          - int vlan 202 
        lines: 
          - ip address 172.18.20.2 255.255.254.0 
          - standby 202 ip 172.18.20.1
          - standby 202 priority 150 
          - standby 202 preempt
          - no shut
    - name: HSRP 203
      ios_config: 
        parents: 
          - int vlan 203 
        lines: 
          - ip address 172.18.22.2 255.255.254.0 
          - standby 203 ip 172.18.22.1
          - standby 203 priority 100
          - standby 203 preempt
          - no shut
    - name: HSRP 204
      ios_config: 
        parents: 
          - int vlan 204 
        lines: 
          - ip address 172.18.24.2 255.255.255.0 
          - standby 204 ip 172.18.24.1
          - standby 204 priority 150 
          - standby 204 preempt
          - no shut

    - name: set int e0/1
      ios_config:
        parents:
          - int e0/1
        lines:
          - no sw
          - no sh
          - ip address 172.16.13.2 255.255.255.0
          - do wr

